version: '3'

services:
  app:
    build:
      context: .
    container_name: qjack-sample-app
    tty: true
    command: bash
    working_dir: /app
    ports:
      - 3000:3000
    volumes:
      - ./:/app
    depends_on:
      - postgres

  postgres:
    image: postgres:15-alpine
    container_name: qjack-sample-postgres
    tty: true
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: '10k'
        max-file: '5'
    environment:
      POSTGRES_USER: qjack
      POSTGRES_PASSWORD: password
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
      PGSSLMODE: disable
    ports:
      - 5432:5432
    volumes:
      - qjack-sample-data:/var/lib/postgresql/data

volumes:
  qjack-example-data:
    name: qjack-sample-data
    driver: local
