version: '3'

services:
  app:
    build:
      context: .
    tty: true
    command: bash
    working_dir: /app
    volumes:
      - ../:/app
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    tty: true
    command: postgres -c log_destination=stderr -c log_statement=all -c log_connections=on -c log_disconnections=on
    logging:
      options:
        max-size: '10k'
        max-file: '5'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: host
      POSTGRES_PORT: 5432
      POSTGRES_DB: db
      PGSSLMODE: disable
    ports:
      - '5432:5432'
    volumes:
      - qjack-sample-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  qjack-sample-data:
    driver: local
